"""initial

Revision ID: 7d2b1fb9ae2c
Revises: 
Create Date: 2026-03-06 20:14:43.472399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d2b1fb9ae2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_by_device_id', sa.String(length=255), nullable=False),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('drive_time_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('encoded_polyline', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('osm_id', sa.String(), nullable=False),
    sa.Column('osm_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('best_time_to_visit', sa.String(length=100), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('images_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id', 'osm_type', name='uq_places_osm_id_osm_type')
    )
    # idx_places_geog is auto-created by GeoAlchemy2 Geography column
    op.create_index('ix_places_category', 'places', ['category'], unique=False)
    op.create_index('ix_places_geog_active', 'places', ['geog'], unique=False, postgresql_using='gist', postgresql_where=sa.text('is_active IS true'))
    op.create_index('ix_places_name_trgm', 'places', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_places_rating_desc', 'places', [sa.literal_column('rating DESC')], unique=False)
    op.create_table('active_route_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adventure_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_stop_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False),
    sa.Column('completed_stops', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_known_lat', sa.Float(), nullable=True),
    sa.Column('last_known_lng', sa.Float(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventure_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adventure_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('drive_time_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_to_spend_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adventure_id', 'order', name='uq_adventure_stops_adventure_order')
    )
    op.create_table('saved_adventures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('adventure_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'adventure_id', name='uq_saved_adventures_device_adventure')
    )
    op.create_index('ix_saved_adventures_device_id', 'saved_adventures', ['device_id'], unique=False)
    op.create_table('saved_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'place_id', name='uq_saved_places_device_place')
    )
    op.create_index('ix_saved_places_device_id', 'saved_places', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_places_device_id', table_name='saved_places')
    op.drop_table('saved_places')
    op.drop_index('ix_saved_adventures_device_id', table_name='saved_adventures')
    op.drop_table('saved_adventures')
    op.drop_table('adventure_stops')
    op.drop_table('active_route_sessions')
    op.drop_index('ix_places_rating_desc', table_name='places')
    op.drop_index('ix_places_name_trgm', table_name='places', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_places_geog_active', table_name='places', postgresql_using='gist', postgresql_where=sa.text('is_active IS true'))
    op.drop_index('ix_places_category', table_name='places')
    # idx_places_geog is auto-dropped with the table (created by GeoAlchemy2)
    op.drop_table('places')
    op.drop_table('adventures')
    # ### end Alembic commands ###
